const fileFormats = {
    // Images
    jpg: "image",
    jpeg: "image",
    png: "image",
    gif: "image",
    bmp: "image",
    webp: "image",
    svg: "image",
    tif: "image",
    tiff: "image",
    ico: "image",
    heic: "image",

    // Videos
    mp4: "video",
    mov: "video",
    avi: "video",
    mkv: "video",
    flv: "video",
    wmv: "video",
    webm: "video",
    mpeg: "video",
    mpg: "video",

    // Audios
    mp3: "audio",
    wav: "audio",
    aac: "audio",
    flac: "audio",
    ogg: "audio",
    m4a: "audio",
    wma: "audio",
    opus: "audio",

    // Documents
    pdf: "pdfDocument",
    doc: "document",
    docx: "document",
    xls: "document",
    xlsx: "document",
    ppt: "document",
    pptx: "document",
    txt: "document",
    rtf: "document",
    odt: "document",
    csv: "document",
    md: "document",
    json: "document",
    xml: "document",
    yaml: "document",
    yml: "document",

    // Archives
    zip: "archive",
    rar: "archive",
    tar: "archive",
    gz: "archive",
    bz2: "archive",
    tgz: "archive",
    xz: "archive",

    // Code
    js: "code",
    ts: "code",
    jsx: "code",
    tsx: "code",
    html: "code",
    css: "code",
    scss: "code",
    sass: "code",
    py: "code",
    java: "code",
    c: "code",
    cpp: "code",
    cs: "code",
    go: "code",
    rb: "code",
    php: "code",
    sh: "code",
    swift: "code",
    kotlin: "code",
    lua: "code",
    sql: "code",

    // Executables / Others
    exe: "executable",
    dmg: "executable",
    apk: "executable",
    app: "executable",
    bin: "executable",
    iso: "diskimage",
    deb: "package",
    rpm: "package",

    // Others

    aep: "aftereffects",
    ae: "aftereffects",
    ai: "illustrator",
    psd: "photoshop",
    pr: "premiere",
    prproj: "premiere",
    prproj: "premiere",
    "3gp": "video",
    "7z": "archive",
    "7zip": "archive",
    "001": "archive",
};

export default fileFormats;
